# global configs
Global:
  mode: inference    # evaluation, inference
  category: segmentation3d
# model architecture
Model:
  name: squeezesegv3
  backend: powervr_grpc   #clas_sim, paddle, powervr, powervr_grpc
  head_ops:
    - ReOutputsKey:
        pred_img_label: tvm_infer_0_out_0.bin
    - Reshape:
        pred_img_label: [1, 64, 1024]

  PowerVR_gRPC:
    pvr_server: 10.80.51.219
    input_name: samples
    output_shape: [1, 64, 1024]

Infer:
  infer_datas:
    velodyne:
      - C:\REPOS\Paddle3D\datasets\SemanticKITTI\sequences\00\velodyne\000010.bin
  batch_size: 1
  transform_ops:
    - LoadSemanticKITTIRange:
        project_label: false
        # labels: C:\REPOS\Paddle3D\datasets\SemanticKITTI\sequences\00\labels\000010.label
    - NormalizeRangeImage:
        mean: [12.12,10.88,0.23,-1.04,0.21]
        std: [12.32,11.47,6.91,0.86,0.16 ]
    - MaskAndExpand:
        proj_mask: "proj_mask.npy"
  postprocess_ops:
    - Select:
        proj_x: "proj_x.npy"
        proj_y: "proj_y.npy"
    - VisualizePoints3D:
        output_dir: ./output_dir  # save mode
                                  # show mode if output_dir is None